export interface Appointment {
    id?: number,
    created?: string,
    modified?: string,
    medical_offices_id?: number,
    studies_value?: number,
    studies_id?: number,
    type?: number,
    observations?: string,
    expected_date?: string,
    this_complement?: number,
    quantity?: number,
    state_therapy?: number,
    attend_therapy?: number,
    continues_therapy?: number,
    clients_id?: number,
    attentions?: Array<any>,
    medical_office?: {
        id?: number,
        code?: number,
        name?: string,
        description?: string,
        created?: string,
        modified?: string,
        state?: number,
        centers_id?: number,
        therapy?: number
    },
    study?: {
        id?: number,
        cup?: number,
        name?: string,
        specializations_id?: number,
        average_time?: number,
        type?: number,
        format_types_id?: number,
        coments?: string,
        radiation_dose?: number,
        created?: string,
        modified?: string,
        users_id?: number,
        state?: number,
        category_studies_id?: number,
        type_study?: number
    },
    _matchingData?: {
        Orders?: {
            id?: number,
            order_consec?: string,
            validator?: string,
            calculated_age?: number,
            observations?: string,
            subtotal?: number,
            discount?: number,
            donation?: number,
            total?: number,
            total_cancel?: number,
            copayment?: number,
            discount_type?: string,
            created?: string,
            modified?: string,
            clients_id?: number,
            rates_id?: number,
            users_id?: number,
            patients_id?: number,
            external_specialists_id?: number,
            service_type_id?: number,
            centers_id?: number,
            order_states_id?: number,
            cie_ten_codes_id?: number,
            consultation_endings_id?: number,
            external_causes_id?: number,
            cost_centers_id?: number,
            bill_types_id?: number,
            signature?: string
        },
        Patients?: {
            id?: number,
            people_id?: number,
            users_id?: number,
            created?: string,
            modified?: string,
            zone_id?: number,
            regimes_id?: number,
            permanent_diagnostic?: string,
            eps_id?: number,
            affiliation_type?: Number,
            education_level_id?: number,
            ocupations_id?: number,
            ethics_id?: number
        },
        People?: {
            id?: number,
            document_types_id?: number,
            identification?: number,
            first_name?: string,
            middle_name?: string,
            last_name?: string,
            last_name_two?: string,
            birthdate?: string,
            gender?: number,
            address?: string,
            phone?: string,
            email?: string,
            created?: string,
            modified?: string,
            municipalities_id?: number,
            user_creation?: number,
            phone_sms?: string,
            check_send_sms?: number
        },
        Clients?: {
            name?: string
        },
        AppointmentDates?: {
            id?: number,
            date_time_ini?: string,
            dateTimeIni?: string,
            dateTimeEnd?: string
        },
        AppointmentStates?: {
            state?: string,
            id?: number
        },
        DeliveryResults?: {
            id?: number
        },
        OrderAppointments?: {
            id?: number,
            orders_id?: number,
            appointments_id?: number,
            created?: string,
            modified?: string
        }
    }
}